pipeline:
  identifier: Build_KnightMode_HarnessTerraform_1724591576927
  name: Build HarnessTerraform
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1724591291963
        repoName: KnightMode/HarnessTerraform
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    connectorRef: account.harnessImage
                    image: ubuntu
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              harnessImageConnectorRef: account.harnessImage
              os: Linux
        type: CI
        description: ""
